version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: courses
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
