version: '3.8'

services:
  postgres:
    image: 'postgres:15' # Usa a versão 15 do PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_DB: courses
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d courses"]
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build: .
    container_name: spring_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courses
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - '8080:8080'
    restart: always

volumes:
  postgres_data:
