

services:
  api:
    build: .
    container_name: minha-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.kphcxuvtgmgymnfodofw.supabase.co:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vymfej-zyrpyb-jaWcy6
    ports:
      - "8080:8080"
    networks:
      - minha_rede

  db:
    image: postgres:latest
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vymfej-zyrpyb-jaWcy6
    ports:
      - "5432:5432"
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge